api/urls.py
from django.conf.urls import url
from api import views

urlpatterns = [
    url(r'^IssueBook/$', views.IssueBook.as_view(), name='IssueBook'),
    url(r'^IssueChapter/$', views.IssueChapter.as_view(), name='IssueChapter'),
]

system/urls.py
from django.conf.urls import url
from system import views
from system import api_views

urlpatterns = [
    url(r'^systemPage/$', views.SystemPage.as_view(), name='system'),
    url(r'^navigationList/$', views.NavigationList.as_view(), name='navigation'),
    url(r'^NavigationAdd/$', views.Navigation.as_view(), name='navigationAdd'),
    url(r'^NavigationEdit/$', views.NavigationEdit.as_view(), name='navigationEdit'),
    url(r'^novelList/$', views.NovelList.as_view(), name='bookList'),
    url(r'^chapterGet/$', api_views.ChapterGet.as_view(), name='chapterGet'),
    url(r'^commentList/$', views.CommentView.as_view(), name='comment'),
    url(r'^linkLink/$', views.LinkView.as_view(), name='linkView'),
    url(r'^linkEditView/$', api_views.LinkEditView.as_view(), name='linkEditView'),
    url(r'^adEditView/$', api_views.AdEditView.as_view(), name='adEditView'),
    url(r'^uploadFile/$', api_views.UploadFile.as_view(), name='uploadFile'),
    url(r'^chapterIsPay/$', api_views.ChapterIsPay.as_view(), name='chapterIsPay'),
    url(r'^uploadFile/$', api_views.UploadFile.as_view(), name='uploadFile'),
    url(r'^novelEdit/$', api_views.NovelEdit.as_view(), name='novelEdit'),
    url(r'^navigationEdit_display/$', api_views.Navigation.as_view(), name='navigationEdit_display'),
    url(r'^novelShow/$', api_views.NovelShow.as_view(), name='novelShow'),
    url(r'^adListView/$', views.AdView.as_view(), name='adListView'),
    url(r'^saveMode/$', views.SaveMode.as_view(), name='saveMode'),
    url(r'^normalAccess/$', views.NormalAccess.as_view(), name='normalAccess'),
    url(r'^freezeAccess/$', views.FreezeAccess.as_view(), name='freezeAccess'),
    url(r'^forbidAccess/$', views.ForbidAccess.as_view(), name='forbidAccess'),
]

tl_book/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from system import urls as admin_url
from api import urls as api_url
from web_api import urls as web_api
from web import urls as web_urls
from django.views.generic import RedirectView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(web_urls, namespace='web_system', app_name='web_system')),
    url(r'^admin/', include(admin_url, namespace='admin_system', app_name='admin_system')),
    url(r'^api/', include(api_url, namespace='api_system', app_name='api_system')),
    url(r'^web_api/', include(web_api, namespace='web_api', app_name='web_api')),
    url(r'^favicon\.ico$', RedirectView.as_view(url=r'static/img/favicon.ico')),
]

web/urls.py
from django.conf.urls import url
from web import views

urlpatterns = [
    url(r'^$', views.IndexPage.as_view(), name='indexPage'),
    url(r'^sort/(.+).jsp$', views.SortList.as_view(), name='sortList'),
    url(r'^detail/(.+).jsp$', views.Detail.as_view(), name='detail'),
    url(r'^book/(.+).jsp$', views.Book.as_view(), name='book'),
    url(r'^ranking_list.jsp$', views.OtherList.as_view(), name='rankingList'),  # 排行榜
    url(r'^over.jsp$', views.OtherList.as_view(), name='overList'),  # 完本
    url(r'^serialize.jsp$', views.OtherList.as_view(), name='serializeList'),  # 连载
]

web_api/urls.py
from django.conf.urls import url
from web_api import views

urlpatterns = [
    url(r'^navigation/$', views.Navigation.as_view(), name='navigation'),
    url(r'^getNovel/$', views.GetNovel.as_view(), name='getNovel'),
    url(r'^navigationNovel/$', views.NavigationNovel.as_view(), name='navigationNovel'),
    url(r'^links/$', views.Links.as_view(), name='links'),
    url(r'^sortNovel/$', views.SortNovel.as_view(), name='sortNovel'),
    url(r'^book/$', views.BookData.as_view(), name='book'),
    url(r'^getOther/$', views.GetOther.as_view(), name='getOther'),
    url(r'^search/$', views.Search.as_view(), name='search'),
]

web/templates/index.html
{% extends 'base/base.html' %}

{% block main %}
    <!-- 轮播、最新 -->
    <div class="index_top_row">
        <el-row>
            <el-col :span="4">
                <div class="grid-content bg-purple">&nbsp;</div>
            </el-col>
            <el-col :span="10">
                <div class="grid-content bg-purple">
                    <template>
                        <el-carousel :interval="4000" indicator-position="outside" height="260px">
                            <el-carousel-item v-for="data in focus"><h3 class="medium">
                                <a href="javascript:;" :data-id="data.uuid" ><img  width="100%" height="260px" :src="data.novel_img"></a>
                            </h3>
                            </el-carousel-item>
                        </el-carousel>
                    </template>
                </div>
            </el-col>
            <el-col :span="1">
                <div class="grid-content bg-purple">&nbsp;</div>
            </el-col>
            <el-col :span="5">
                <div class="grid-content bg-purple right">
                    <div class="title">最新发布</div>
                    <ul>
                        <li v-for="data in newest">
                            <el-link type="info" :data-id="data.uuid" :underline="false">[<span v-text="data.categories"></span>]&nbsp;&nbsp;<span
                                    v-text="data.novel_name"></span></el-link>
                        </li>
                    </ul>
                </div>
            </el-col>
            <el-col :span="4">
                <div class="grid-content bg-purple">&nbsp;</div>
            </el-col>
        </el-row>
    </div>
    <!-- 热门推荐 -->
    <div class="index_recommend_hot">
        <el-row>
            <el-col :span="4">
                <div class="grid-content bg-purple">&nbsp;</div>
            </el-col>
            <el-col :span="16">
                <div class="grid-content bg-purple">
                    <div class="left">
                        <strong>热门推荐</strong>
                        <el-divider></el-divider>
                        <div class="article">
                            <article v-for="data in hot">
                                <div class="article_left">
                                    <el-link type="info" :underline="false" :data-id="data.uuid"><img :src="data.novel_img"></el-link>
                                </div>
                                <div class="article_right">
                                    <h4>
                                        <el-link type="info" :underline="false" :data-id="data.uuid" v-text="data.novel_name"></el-link>
                                    </h4>
                                    <div class="article_synopsis" v-text="data.novel_description"></div>
                                    <div class="article_msg">
                                        <div style="float: left"><i class="el-icon-user-solid"></i><span v-text="data.novel_author"></span></div>
                                        <div style="float: right;border: 1px solid #e7e7e7;" v-text="data.categories"></div>
                                    </div>
                                </div>
                            </article>

                        </div>
                    </div>
                    <div class="right">
                        <strong>随机强推</strong>
                        <el-divider></el-divider>
                        <ul>
                            <li v-for="data in random">
                                <el-link href="javascript:;" type="info" :underline="false" :data-id="data.uuid">「<span v-text="data.categories"></span>」</el-link>
                                <el-link href="javascript:;" type="info" :underline="false" class="title" :data-id="data.uuid" v-text="data.novel_name"></el-link>
                            </li>
                        </ul>
                    </div>
                </div>
            </el-col>
            <el-col :span="4">
                <div class="grid-content bg-purple">&nbsp;</div>
            </el-col>
        </el-row>
    </div>
    <!-- 分类列表 -->
    <div class="index_nav_novel">
        <el-row>
            <el-col :span="4">
                <div class="grid-content bg-purple">&nbsp;</div>
            </el-col>
            <el-col :span="16">
                <strong>分类推荐</strong>
                <el-divider></el-divider>
                <div class="list_novel">
                    <article class="nav_list_novel" v-for="nav in navNovel">
                        <h2 v-text="nav.column_name"></h2>
                        <div class="top" v-for="novel in nav.novelList.slice(0,1)">
                            <div class="image">
                                <el-link :data-id="novel.uuid" :underline="false" :title="novel.novel_name">
                                    <el-image :src="novel.novel_img" :alt="novel.novel_name"></el-image>
                                </el-link>
                            </div>
                            <dl>
                                <dt>
                                    <el-link :data-id="novel.uuid" :underline="false" v-text="novel.novel_name"></el-link>
                                </dt>
                                <dd v-text="novel.novel_description"></dd>
                            </dl>
                        </div>
                        <ul>
                            <li v-for="novel in nav.novelList.slice(1,6)">
                                <el-link :data-id="novel.uuid" :underline="false" :title="novel.novel_name" v-text="novel.novel_name"></el-link>
                                <span v-text="novel.novel_author"></span>
                            </li>
                        </ul>
                    </article>
                </div>
            </el-col>
            <el-col :span="4">
                <div class="grid-content bg-purple">&nbsp;</div>
            </el-col>
        </el-row>
    </div>
    <!-- 友情链接 -->
    <div class="links">
        <el-row>
            <el-col :span="4">
                <div class="grid-content bg-purple">&nbsp;</div>
            </el-col>
            <el-col :span="16">
                <div class="grid-content bg-purple">
                    <strong class="el-icon-link">友情链接</strong>
                    <el-divider></el-divider>
                    <div class="links-list">
                        <el-link :href="link.link_url" :underline=" false" icon="el-icon-orange" v-for="link in links" v-text="link.link_name" target="_blank"></el-link>
                    </div>
                </div>
            </el-col>
            <el-col :span="4">
                <div class="grid-content bg-purple">&nbsp;</div>
            </el-col>
        </el-row>
    </div>
{% endblock %}

{% block script %}
    <script type="text/javascript">
        var Main = {
            data() {
                return {
                    title:'',
                    keywords:'',
                    description:'',
                    search: {
                        key: ''
                    },
                    //          loginForm: {},
                    //         regForm: {},
                    //        login: false,
                    //        formLabelWidth: '80px',
                    //       code_img: {
                    //           url: '',
                    //          status: false,
                    //         button: true,
                    //        img_show: false
                    //    },
                    //    login_or_reg: {
                    //       'title': '用户登录',
                    //       status: true
                    //   },
                    navList: [],
                    newest: [],
                    hot: [],
                    random: [],
                    column_display: [],
                    navNovel: [],
                    links: [],
                    focus: []
                };
            },
            methods: {
                loadNav: function () {
                    reslut = ajax(this, 'GET', {'parse': 'all'}, '{% url "web_api:navigation" %}');
                    if (reslut.code === 0) {
                        this.navList = reslut.nav_all;
                        this.column_display = reslut.column_display;
                    }
                },
                handleNavSelect: function (key, keyPath) {
                    handleNavSelect(key, keyPath)
                },
                handSearch: function () {
                    var key = this.search.key;
                    console.log(key)
                },
                /*  handleClose: function (done) {
                      done()
                      this.code_img = {
                          url: '',
                          status: false,
                          button: true,
                          img_show: false
                      } // 重置验证码
                  },
                  onSubmit: function () {
                      console.log(this.loginForm)
                  },
                  get_v_code: function () {
                      // 获取验证码
                      this.code_img.url = 'https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c25941171jpeg.jpeg';
                      this.code_img.img_show = true; // 显示验证码
                      this.code_img.button = false; // 隐藏验证码按钮
                  },
                  reg: function () {
                      this.login_or_reg.status = false;
                      this.login_or_reg.title = "用户注册面板";
                  },
                  login_page: function () {
                      this.login_or_reg.status = true;
                      this.login_or_reg.title = "用户登录面板";
                  },
                  recharge: function () {
                      this.$prompt('请输入邮箱', '提示', {
                          confirmButtonText: '确定',
                          cancelButtonText: '取消',
                          inputPattern: /[\w!#$%&'*+/=?^_`{|}~-]+(?:\.[\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[\w](?:[\w-]*[\w])?\.)+[\w](?:[\w-]*[\w])?/,
                          inputErrorMessage: '邮箱格式不正确'
                      }).then(({
                                   value
                               }) => {
                          this.$message({
                              type: 'success',
                              message: '你的邮箱是: ' + value
                          });
                      }).catch(() => {
                      });
                  }

                 */
            },
            mounted() {
                // 初始化数据--> 调用方法
                this.loadNav(); // 加载导航
                reslut = ajax(this, 'GET', {'type': 'newest', 'limit': 6}, '{% url "web_api:getNovel" %}'); // 最新
                if (reslut.code === 0) {
                    this.newest = reslut.dataList;
                }
                reslut = ajax(this, 'GET', {'type': 'hot', 'limit': 9}, '{% url "web_api:getNovel" %}'); // 热推
                if (reslut.code === 0) {
                    this.hot = reslut.dataList
                }
                reslut = ajax(this, 'GET', {'type': 'random', 'limit': 15}, '{% url "web_api:getNovel" %}'); // 随机推
                if (reslut.code === 0) {
                    this.random = reslut.dataList
                }
                reslut = ajax(this, 'GET', {'limit': 6}, '{% url "web_api:navigationNovel" %}'); // 首页分类
                if (reslut.code === 0) {
                    this.navNovel = reslut.navNovel
                }
                reslut = ajax(this, 'GET', {}, '{% url "web_api:links" %}'); // 首页分类
                if (reslut.code === 0) {
                    this.links = reslut.links
                }
                reslut = ajax(this, 'GET', {'type': 'focus', 'limit': 8}, '{% url "web_api:getNovel" %}'); // 首页分类
                if (reslut.code === 0) {
                    this.focus = reslut.dataList
                }
            }
        };
        var Ctor = Vue.extend(Main);
        new Ctor().$mount('#app')
    </script>
{% endblock %}

web/templates/other_list.html
{% extends 'base/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock %}
{% block main %}
    <!-- 条件筛选 -->
    <el-row :gutter="20">
        <el-col :span="4">
            <div class="grid-content bg-purple">&nbsp;</div>
        </el-col>
        <el-col :span="4">
            <div class="grid-content bg-purple">
                {#                <template>#}
                {#                    <el-tabs value="all" @tab-click="handleClick">#}
                {#                        <el-tab-pane label="全部" name="all">全部</el-tab-pane>#}
                {#                        <el-tab-pane label="男生" name="schoolboy">男生</el-tab-pane>#}
                {#                        <el-tab-pane label="女生" name="schoolgirl">女生</el-tab-pane>#}
                {#                    </el-tabs>#}
                {#                </template>#}
                {#                <el-divider></el-divider>#}
                <!-- 分类 -->
                <div><b>分类</b></div>
                <el-link :underline="false" class="current">全部</el-link>
                <el-link :underline="false" :sort_id="nav.column_link ? nav.column_link:nav.uuid" v-for="nav in navList"><span v-text="nav.column_name"></span></el-link>
                <el-divider></el-divider>
                <div><b>状态</b></div>
                <el-link :underline="false" class="current">全部</el-link>
                <el-link :underline="false" location="{% url 'web_system:serializeList' %}">连载</el-link>
                <el-link :underline="false" location="{% url 'web_system:overList' %}">完本</el-link>
                <el-divider></el-divider>
                {#                <div><b>属性</b></div>#}
                {#                <el-link :underline="false" class="current">全部</el-link>#}
                {#                <el-link :underline="false">免费</el-link>#}
                {#                <el-link :underline="false">付费</el-link>#}
            </div>
        </el-col>
        <el-col :span="12">
            <div class="grid-content bg-purple">
                <div class="list">
                    <el-link :underline="false" class="current">综合</el-link>
                    <el-link :underline="false">点击</el-link>
                    <el-link :underline="false">时间</el-link>
                    <el-divider></el-divider>
                    <div class="book_list">
                        <ul>
                            <li v-for="data in page_data.novelList">
                                <div class="book_img">
                                    <el-link :underline="false" :data-id="data.uuid" target="_blank">
                                        <el-image style="width: 100%;" :alt="data.novel_name" :src="data.novel_img"></el-image>
                                    </el-link>
                                </div>
                                <div class="book_info">
                                    <h3>
                                        <el-link :underline="false" target="_blank" :data-id="data.uuid"><span v-text="data.novel_name"></span></el-link>
                                    </h3>
                                    <h4 v-text="data.novel_author"></h4>
                                    <p class="tag"><span class="org" v-text="data.categories"></span><span class="red" v-text="data.novel_state?'已完结':'连载中'"></span><span
                                            class="blue" v-text="data.novel_words"></span></p>
                                    <p class="intro" v-text="data.novel_description.slice(0, 35)"></p>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="page">
                        <el-pagination background layout="prev, pager, next" :total="page_data.num_pages*10" :current-page="page_data.currentPage"
                                       @current-change="current_change"></el-pagination>
                    </div>
                </div>
            </div>
        </el-col>
        <el-col :span="4">
            <div class="grid-content bg-purple">&nbsp;</div>
        </el-col>
    </el-row>
{% endblock %}

{% block script %}
    <script>
        var Main = {
            data() {
                return {
                    title:'',
                    keywords:'',
                    description:'',
                    search: {
                        key: ''
                    },
                    navList: [],
                    column_display: [],
                    page_data: {},
                };
            },
            methods: {
                handleNavSelect: function (key, keyPath) {
                    handleNavSelect(key, keyPath)
                },
                handSearch: function () {
                    var key = this.search.key;
                    console.log(key)
                },//, handleClick: function () {}
                current_change: function (currentPage) {
                    var param = {'page_size': 10, 'cls': '{{ path }}', 'page': currentPage},
                        result = ajax(this, 'GET', param, '{% url "web_api:getOther" %}');
                    if (result.code === 0) {
                        this.page_data = result.data;
                    }
                }
            },
            mounted() {
                result = ajax(this, 'GET', {'parse': 'all'}, '{% url "web_api:navigation" %}');
                if (result.code === 0) {
                    this.navList = result.nav_all;
                    this.column_display = result.column_display;
                }
                result = ajax(this, 'GET', {'cls': '{{ path }}'}, '{% url "web_api:getOther" %}');
                if (result.code === 0) {
                    this.page_data = result.data;
                }
            }
        };
        var Ctor = Vue.extend(Main);
        new Ctor().$mount('#app')
    </script>
{% endblock %}

web/templates/sort.html
{% extends 'base/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock %}
{% block main %}
    <!-- 条件筛选 -->
    <el-row :gutter="20">
        <el-col :span="4">
            <div class="grid-content bg-purple">&nbsp;</div>
        </el-col>
        <el-col :span="4">
            <div class="grid-content bg-purple">
                {#                <template>#}
                {#                    <el-tabs value="all" @tab-click="handleClick">#}
                {#                        <el-tab-pane label="全部" name="all">全部</el-tab-pane>#}
                {#                        <el-tab-pane label="男生" name="schoolboy">男生</el-tab-pane>#}
                {#                        <el-tab-pane label="女生" name="schoolgirl">女生</el-tab-pane>#}
                {#                    </el-tabs>#}
                {#                </template>#}
                {#                <el-divider></el-divider>#}
                <!-- 分类 -->
                <div><b>分类</b></div>
                <el-link :underline="false" class="current">全部</el-link>
                <el-link :underline="false" :sort_id="nav.column_link ? nav.column_link:nav.uuid" v-for="nav in navList"><span v-text="nav.column_name"></span></el-link>
                <el-divider></el-divider>
                <div><b>状态</b></div>
                <el-link :underline="false" class="current">全部</el-link>
                <el-link :underline="false" location="{% url 'web_system:serializeList' %}">连载</el-link>
                <el-link :underline="false" location="{% url 'web_system:overList' %}">完本</el-link>
                <el-divider></el-divider>
                {#                <div><b>属性</b></div>#}
                {#                <el-link :underline="false" class="current">全部</el-link>#}
                {#                <el-link :underline="false">免费</el-link>#}
                {#                <el-link :underline="false">付费</el-link>#}
            </div>
        </el-col>
        <el-col :span="12">
            <div class="grid-content bg-purple">
                <div class="list">
                    <el-link :underline="false" class="current">综合</el-link>
                    <el-link :underline="false">点击</el-link>
                    <el-link :underline="false">时间</el-link>
                    <el-divider></el-divider>
                    <div class="book_list">
                        <ul>
                            <li v-for="data in page_data.novelList">
                                <div class="book_img">
                                    <el-link :underline="false" :data-id="data.uuid" target="_blank">
                                        <el-image style="width: 100%;" :alt="data.novel_name" :src="data.novel_img"></el-image>
                                    </el-link>
                                </div>
                                <div class="book_info">
                                    <h3>
                                        <el-link :underline="false" target="_blank" :data-id="data.uuid"><span v-text="data.novel_name"></span></el-link>
                                    </h3>
                                    <h4 v-text="data.novel_author"></h4>
                                    <p class="tag"><span class="org" v-text="data.categories"></span><span class="red" v-text="data.novel_state?'已完结':'连载中'"></span><span
                                            class="blue" v-text="data.novel_words"></span></p>
                                    <p class="intro" v-text="data.novel_description.slice(0, 35)"></p>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="page">
                        <el-pagination background layout="prev, pager, next" :total="page_data.num_pages*10" :current-page="page_data.currentPage"
                                       @current-change="current_change"></el-pagination>
                    </div>
                </div>
            </div>
        </el-col>
        <el-col :span="4">
            <div class="grid-content bg-purple">&nbsp;</div>
        </el-col>
    </el-row>
{% endblock %}

{% block script %}
    <script>
        var sort_id = "{{ uid }}";
        var Main = {
            data() {
                return {
                    title:'',
                    keywords:'',
                    description:'',
                    search: {
                        key: ''
                    },
                    navList: [],
                    column_display: [],
                    page_data: {},
                };
            },
            methods: {
                handleNavSelect: function (key, keyPath) {
                    handleNavSelect(key, keyPath)
                },
                handSearch: function () {
                    var key = this.search.key;
                    console.log(key)
                },//, handleClick: function () {}
                current_change: function (currentPage) {
                    var param = {'page_size': 10, 'uid': sort_id, 'page': currentPage},
                        result = ajax(this, 'GET', param, '{% url "web_api:sortNovel" %}');
                    if (result.code === 0) {
                        this.page_data = result.data;
                    }
                }
            },
            mounted() {
                result = ajax(this, 'GET', {'parse': 'all'}, '{% url "web_api:navigation" %}');
                if (result.code === 0) {
                    this.navList = result.nav_all;
                    this.column_display = result.column_display;
                }
                result = ajax(this, 'GET', {'uid': sort_id}, '{% url "web_api:sortNovel" %}');
                if (result.code === 0) {
                    this.page_data = result.data;
                }
            }
        };
        var Ctor = Vue.extend(Main);
        new Ctor().$mount('#app')
    </script>
{% endblock %}