api/urls.py
from django.conf.urls import url
from api import views

urlpatterns = [
    url(r'^IssueBook/$', views.IssueBook.as_view(), name='IssueBook'),
    url(r'^IssueChapter/$', views.IssueChapter.as_view(), name='IssueChapter'),
]

system/urls.py
from django.conf.urls import url
from system import views
from system import api_views

urlpatterns = [
    url(r'^systemPage/$', views.SystemPage.as_view(), name='system'),
    url(r'^navigationList/$', views.NavigationList.as_view(), name='navigation'),
    url(r'^NavigationAdd/$', views.Navigation.as_view(), name='navigationAdd'),
    url(r'^NavigationEdit/$', views.NavigationEdit.as_view(), name='navigationEdit'),
    url(r'^novelList/$', views.NovelList.as_view(), name='bookList'),
    url(r'^chapterGet/$', api_views.ChapterGet.as_view(), name='chapterGet'),
    url(r'^commentList/$', views.CommentView.as_view(), name='comment'),
    url(r'^linkLink/$', views.LinkView.as_view(), name='linkView'),
    url(r'^linkEditView/$', api_views.LinkEditView.as_view(), name='linkEditView'),
    url(r'^adEditView/$', api_views.AdEditView.as_view(), name='adEditView'),
    url(r'^uploadFile/$', api_views.UploadFile.as_view(), name='uploadFile'),
    url(r'^chapterIsPay/$', api_views.ChapterIsPay.as_view(), name='chapterIsPay'),
    url(r'^uploadFile/$', api_views.UploadFile.as_view(), name='uploadFile'),
    url(r'^novelEdit/$', api_views.NovelEdit.as_view(), name='novelEdit'),
    url(r'^navigationEdit_display/$', api_views.Navigation.as_view(), name='navigationEdit_display'),
    url(r'^novelShow/$', api_views.NovelShow.as_view(), name='novelShow'),
    url(r'^adListView/$', views.AdView.as_view(), name='adListView'),
    url(r'^saveMode/$', views.SaveMode.as_view(), name='saveMode'),
    url(r'^normalAccess/$', views.NormalAccess.as_view(), name='normalAccess'),
    url(r'^freezeAccess/$', views.FreezeAccess.as_view(), name='freezeAccess'),
    url(r'^forbidAccess/$', views.ForbidAccess.as_view(), name='forbidAccess'),
]

tl_book/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from system import urls as admin_url
from api import urls as api_url
from web_api import urls as web_api
from web import urls as web_urls
from django.views.generic import RedirectView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(web_urls, namespace='web_system', app_name='web_system')),
    url(r'^admin/', include(admin_url, namespace='admin_system', app_name='admin_system')),
    url(r'^api/', include(api_url, namespace='api_system', app_name='api_system')),
    url(r'^web_api/', include(web_api, namespace='web_api', app_name='web_api')),
    url(r'^favicon\.ico$', RedirectView.as_view(url=r'static/img/favicon.ico')),
]

system/views.py
import time, json
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponse, QueryDict, Http404, JsonResponse
from django.shortcuts import render
from django.views import View
from public import update_data, create_data, delete_data, verify_obj, PaginatorPage, access_auto_page, delete_access, categoryList
from system.forms import *
from system.models import *
from public.redis_pool import conn
from tl_book.settings import NORMAL_AUTH_TIME, FREEZE_TIME


class SystemPage(View):  # 站点设置

    @method_decorator(login_required)
    def get(self, request):
        system = SystemModel.objects.first()
        if system is None:
            system = SystemModel()  # todo 建议统一处理初始化系统
            system.save()
        return render(request, 'set_system.html', context={'data': dict(system)})

    @method_decorator(login_required)
    def post(self, request):
        return update_data(request, SystemForm, SystemModel, request.POST.get('uuid'))

    def http_method_not_allowed(self, request, *args, **kwargs):
        return HttpResponse(f'限制的{request.method}请求，请使用其他请求！')


class NavigationList(View):  # 分类列表

    @method_decorator(login_required)
    def get(self, request):
        return render(request, 'navigationList.html', context={'NavList': NavigationModel.objects.order_by('-create_time').filter(is_delete=False).all()})

    @method_decorator(login_required)
    def delete(self, request):
        uuid = QueryDict(request.body).get('uuid')
        return delete_data(uuid, NavigationModel)


class Navigation(View):  # 添加分类

    @method_decorator(login_required)
    def get(self, request):
        data = categoryList(NavigationModel.objects.filter(is_delete=False).values_list('uuid', 'column_name', 'column_parent'))
        return JsonResponse({'code': 0, 'category': data})

    @method_decorator(login_required)
    def post(self, request):
        return create_data(request, NavigationForm, NavigationModel)


class NavigationEdit(View):  # 修改分类

    @method_decorator(login_required)
    def get(self, request):
        uuid = request.GET.get('uuid', 'None')
        obj = NavigationModel.objects.filter(uuid=uuid).first()
        if not verify_obj(obj): return JsonResponse({'code': 4, 'msg': '参数错误', 'error': '未成功获取数据'})
        return JsonResponse({"code": 0, 'data': dict(obj)})

    @method_decorator(login_required)
    def post(self, request):
        uuid = request.POST.get('uuid', 'None')
        if uuid == request.POST.get('column_parent'): return JsonResponse({'code': 1, 'msg': '更新数据失败', 'error': '上级分类不可选择自己'})
        return update_data(request, NavigationEditForm, NavigationModel, uuid)


class NovelList(View):  # 小说列表

    @method_decorator(login_required)
    def get(self, request):
        search = request.GET.get('search')
        if search:
            data_list, page = PaginatorPage(request, NovelModel.objects.filter(novel_name=search).all())
        else:
            data_list, page = PaginatorPage(request, NovelModel.objects.order_by('-create_time').all())
        return render(request, 'novelList.html', context={'novelList': data_list, 'page': page})

    @method_decorator(login_required)
    def delete(self, request):
        uuid = QueryDict(request.body).get('uuid')
        try:
            obj = NovelModel.objects.filter(uuid=uuid).first()
            if not verify_obj(obj): return JsonResponse({'code': 1, 'msg': '删除数据失败', 'error': '参数有误，未检测到数据'})
            ChapterModel.objects.filter(novel=obj).delete()
            obj.delete()
        except Exception as e:
            return JsonResponse({'code': 4, 'msg': '删除数据异常', 'error': str(e)})
        return JsonResponse({'code': 0, 'msg': '删除数据成功'})

    @method_decorator(login_required)
    def post(self, request):
        uuidList = request.POST.get('uuidList').split('|*TL*|')
        if not uuidList: return JsonResponse({'code': 1, 'msg': '删除数据失败', 'error': '参数有误，未检测到参数'})
        for uuid in uuidList:
            try:
                obj = NovelModel.objects.filter(uuid=uuid)
                if not obj.first(): continue
                ChapterModel.objects.filter(novel=obj).delete()
                obj.delete()
            except Exception as e:
                return JsonResponse({'code': 4, 'msg': '删除数据异常', 'error': str(e)})
        return JsonResponse({'code': 0, 'msg': f'删除{len(uuidList)}条数据成功'})


class CommentView(View):  # 评论列表

    @method_decorator(login_required)
    def get(self, request):
        search = request.GET.get('search')
        if search:
            novel = NovelModel.objects.filter(novel_name=search).first()
            data_list, page = PaginatorPage(request, Comment_Model.objects.filter(content_uuid=novel).all())
        else:
            data_list, page = PaginatorPage(request, Comment_Model.objects.order_by('-create_time').all())
        return render(request, 'commentList.html', context={'dataList': data_list, 'page': page})

    @method_decorator(login_required)
    def delete(self, request):
        uuid = QueryDict(request.body).get('uuid')
        return delete_data(uuid, Comment_Model)


class LinkView(View):  # 链接列表

    @method_decorator(login_required)
    def get(self, request):
        data_list, page = PaginatorPage(request,
                                        Blogroll_Model.objects.order_by('-create_time').all().values('uuid', 'update_time', 'link_name', 'link_url', 'link_end_date',
                                                                                                     'link_remark'))
        return render(request, 'linkList.html', context={'dataList': data_list, 'page': page})

    @method_decorator(login_required)
    def delete(self, request):
        uuid = QueryDict(request.body).get('uuid')
        return delete_data(uuid, Blogroll_Model)

    @method_decorator(login_required)
    def post(self, request):
        return create_data(request, LinkForm, Blogroll_Model)


class AdView(View):

    @method_decorator(login_required)
    def get(self, request):
        data_list, page = PaginatorPage(request, Ad_Model.objects.order_by('-create_time').all().values('uuid', 'update_time', 'ad_name', 'ad_end_date', 'ad_remark'))
        return render(request, 'adList.html', context={'dataList': data_list, 'page': page})

    @method_decorator(login_required)
    def post(self, request):
        return create_data(request, AdForm, Ad_Model)

    @method_decorator(login_required)
    def delete(self, request):
        uuid = QueryDict(request.body).get('uuid')
        return delete_data(uuid, Ad_Model)


class SaveMode(View):
    @method_decorator(login_required)
    def get(self, request):
        obj = Save_Model.objects.first()
        if not obj: obj = Save_Model.objects.create()  # todo 建议统一初始化

        return render(request, 'save.html', {'data': dict(obj)})

    @method_decorator(login_required)
    def post(self, request):
        uuid = request.POST.get('uuid')
        return update_data(request, SaveForm, Save_Model, uuid)


class NormalAccess(View):
    @method_decorator(login_required)
    def get(self, request):
        result = [{}]
        result_list = conn.hgetall('NormalAccess')
        for k, v in result_list.items():
            value = json.loads(v.decode())
            value['ip'] = k.decode()
            b = (time.time() - value['first_time']) > NORMAL_AUTH_TIME
            if not b: result.append(value)
        dataList, page = access_auto_page(request, result)
        return render(request, 'normalList.html', context={'dataList': dataList, 'page': page})

    @method_decorator(login_required)
    def post(self, request):
        ip = request.POST.get('ip')
        try:
            try:
                d = json.loads(conn.hget('NormalAccess', ip).decode())
            except Exception as e:
                return JsonResponse({'code': 4, 'msg': f'IP读取出错:{e}'})
            d['freeze_time'] = time.time()
            result = conn.hset('FreezeAccess', ip, json.dumps(d))
            if result:
                conn.hdel('NormalAccess', ip)
                return JsonResponse({'code': 0})
            return JsonResponse({'code': 1, 'msg': '冻结失败，或已存在冻结'})
        except Exception as e:
            return JsonResponse({'code': 4, 'msg': f'冻结处理异常：{str(e)}'})

    @method_decorator(login_required)
    def delete(self, request):
        ip = QueryDict(request.body).get('uuid')
        return delete_access(conn, ip, 'NormalAccess')


class FreezeAccess(View):
    @method_decorator(login_required)
    def get(self, request):
        result = [{}]
        result_list = conn.hgetall('FreezeAccess')
        for k, v in result_list.items():
            value = json.loads(v.decode())
            value['ip'] = k.decode()
            b = ((time.time() - value['freeze_time']) / 60) >= FREEZE_TIME
            if not b: result.append(value)
        dataList, page = access_auto_page(request, result)
        return render(request, 'freezeList.html', context={'dataList': dataList, 'page': page})

    @method_decorator(login_required)
    def post(self, request):
        ip = request.POST.get('ip')
        try:
            try:
                d = json.loads(conn.hget('FreezeAccess', ip).decode())
            except Exception as e:
                return JsonResponse({'code': 4, 'msg': f'IP读取出错:{e}'})
            d['forbid_time'] = time.time()
            result = conn.hset('ForbidAccess', ip, json.dumps(d))
            if result:
                conn.hdel('FreezeAccess', ip)
                return JsonResponse({'code': 0})
            return JsonResponse({'code': 1, 'msg': '添加黑名单失败，或已存在黑名单'})
        except Exception as e:
            return JsonResponse({'code': 4, 'msg': f'处理异常：{str(e)}'})

    @method_decorator(login_required)
    def delete(self, request):
        ip = QueryDict(request.body).get('uuid')
        return delete_access(conn, ip, 'FreezeAccess')


class ForbidAccess(View):

system/templates/commentList.html
{% extends 'admin/base.html' %}
{% load custom_filters staticfiles %}
{% block content %}
    <style>
        .cell {
            text-align: center;
        }

        div[class="el-input"] {
            width: 220px;
        }
    </style>
    <div id="app">
        <el-row>
            <div style="float: right">
                <el-input v-model="search" placeholder="请输入书名"></el-input>
                <el-button type="primary" @click="searchSub">查找</el-button>
            </div>
        </el-row>
        <br/>
        <el-table :data="tableData" border style="width: 100%" @selection-change="handleSelectionChange">
            <el-table-column type="selection" width="55"></el-table-column>
            <el-table-column prop="uuid" label="小说编号" width="100" show-overflow-tooltip></el-table-column>
            <el-table-column prop="novel_name" label="小说名称" width="200" show-overflow-tooltip></el-table-column>
            <el-table-column prop="user_qq" label="评论QQ" width="100" show-overflow-tooltip></el-table-column>
            <el-table-column prop="user_name" label="评论用户" width="200" show-overflow-tooltip></el-table-column>
            <el-table-column prop="comment" label="评论内容" width="400" show-overflow-tooltip></el-table-column>
            <el-table-column prop="other" label="其他操作" fixed="right">
                <template slot-scope="scope">
                    <el-button size="mini" type="danger" @click="handleDelete(scope.$index, scope.row)">删除</el-button>
                </template>
            </el-table-column>
        </el-table>
        <br/>

        <el-pagination background layout="prev, pager, next" :total="total" hide-on-single-page @current-change="current_change" :current-page="currentPage"></el-pagination>

    </div>
    <script src="{% static 'js/public.js' %}" type="text/javascript"></script>
    <script>
        var Main = {
            data() {
                return {
                    search: "{{ request.GET.search }}",
                    total: {{ page.num_pages }}0,
                    currentPage: {{ dataList.number }},
                    tableData: [
                        {% for data in dataList.object_list %}
                            {
                                'uuid': '{{ data.uuid }}',
                                'novel_name': '{{ data.content_uuid.novel_name }}',
                                'comment': '{{ data.comment_txt }}',
                                'user_qq': '{{ data.user_qq }}',
                                'user_name': '{{ data.user_name }}'
                            }
                        {% endfor %}
                    ],
                }
            }
            , methods: {
                handleDelete: function (index, row) {
                    Delete(this, index, row);
                },
                handleSelectionChange: function (val) {
                    this.multipleSelection = val;
                },
                current_change: function (currentPage) {
                    window.location.href = '?page=' + currentPage + '&search=' + this.search;
                },
                searchSub: function () {
                    if (this.search === '') {
                        this.$message.error('请输入查找值...');
                        return NaN
                    }
                    window.location.href = '{% url 'admin_system:comment' %}?search=' + this.search;
                }
            }
        };
        var Ctor = Vue.extend(Main);
        new Ctor().$mount('#app');
    </script>
{% endblock %}

system/templates/forbidList.html
{% extends 'admin/base.html' %}
{% load custom_filters staticfiles %}
{% block content %}
    <style>
        .cell {
            text-align: center;
        }

        div[class="el-input"] {
            width: 220px;
        }
    </style>
    <div id="app">
        <template>
            <el-table :data="tableData" style="width: 100%" border>
                <el-table-column label="IP" prop="ip"></el-table-column>
                <el-table-column label="访问次数" prop="visit"></el-table-column>
                <el-table-column label="初次访问" prop="time"></el-table-column>
                <el-table-column label="最新访问" prop="first_time"></el-table-column>
                <el-table-column label="拉黑时间" prop="forbid_time"></el-table-column>
                <el-table-column label="操作" width="200">
                    <template slot-scope="scope">
                        <el-button size="mini" type="danger" @click="handleDelete(scope.$index, scope.row)">移除</el-button>
                    </template>
                </el-table-column>
            </el-table>
        </template>
        <br/>

        <el-pagination background layout="prev, pager, next" :total="total" hide-on-single-page @current-change="current_change" :current-page="currentPage" style="text-align: right;"></el-pagination>

    </div>
    <script src="{% static 'js/public.js' %}" type="text/javascript"></script>
    <script>
        var Main = {
            data() {
                return {
                    total: {{ page.pages }}0,
                    currentPage: {{ page.current|default:1 }},
                    tableData: [
                        {% for data in dataList %}
                            {
                                ip: '{{ data.ip }}',
                                uuid: '{{ data.ip }}',
                                visit: '{{ data.visit }}',
                                first_time: '{{ data.first_time|time_str }}',
                                forbid_time: '{{ data.forbid_time|time_str }}',
                                time: '{{ data.time|time_str }}',
                            },
                        {% endfor %}
                    ],
                    formLabelWidth: '120px',
                }
            }
            , methods: {
                handleDelete: function (index, row) {
                    Delete(this, index, row);
                },
                current_change: function (currentPage) {
                    window.location.href = '?page=' + currentPage;
                }
            }
        };
        var Ctor = Vue.extend(Main);
        new Ctor().$mount('#app');
    </script>
{% endblock %}

system/templates/navigationList.html
{% extends 'admin/base.html' %}
{% load custom_filters staticfiles %}
{% block content %}
    <style>
        .cell {
            text-align: center;
        }

        #edit_form > div {
            top: 30%;
            left: 30%;
        }
    </style>
    <div id="app">
        <el-row>
            <el-popover placement="right" width="500" trigger="click">
                <el-form ref="form" :model="form" label-width="80px">
                    <el-form-item label="分类名称">
                        <el-input v-model="form.column_name" style="max-width: 300px"></el-input>
                    </el-form-item>
                    <el-form-item label="所属分类">
                        <el-cascader v-model="form.column_parent" :options="options" :props="{ expandTrigger: 'hover' }" placeholder="请选择分类"></el-cascader>
                    </el-form-item>
                    <el-form-item label="分类排序">
                        <el-input v-model="form.column_order" type="number"></el-input>
                    </el-form-item>
                    <el-form-item label="站外链接">
                        <el-input v-model="form.column_link" placeholder="http://"></el-input>
                    </el-form-item>
                    <el-form-item label="关键词">
                        <el-input type="textarea" autosize placeholder="请输入关键词" v-model="form.column_keyword"></el-input>
                    </el-form-item>
                    <el-form-item label="分类描述">
                        <el-input type="textarea" v-model="form.column_description" :autosize="{ minRows: 2, maxRows: 4}"></el-input>
                    </el-form-item>
                    <el-form-item>
                        <el-button @click.prevent="onAddSubmit" type="success" class="el-button--primary">保存添加</el-button>
                        <el-button @click="cancelClick">取消</el-button>
                    </el-form-item>
                </el-form>
                <el-button type="primary" icon="el-icon-plus" slot="reference" @click="onGetCategory">增加</el-button>
            </el-popover>
            <el-button plain icon="el-icon-refresh-right"></el-button>
        </el-row>
        <br>
        <el-table :data="tableData" border style="width: 100%">
            <el-table-column property="uuid" label="分类编号" width="350"></el-table-column>
            <el-table-column property="column_name" label="分类名称" width="160"></el-table-column>
            <el-table-column property="column_parent" label="上级分类" width="160"></el-table-column>
            <el-table-column property="bookNum" label="小说本数" width="80"></el-table-column>
            <el-table-column property="update_time" label="修改时间" width="180"></el-table-column>
            <el-table-column label="首页显示" width="180">
                <template slot-scope="scope_">
                    <el-switch v-model="scope_.row.column_index_show" active-text="显示" inactive-text="隐藏" @change="index_show(scope_.$index,scope_.row)"></el-switch>
                </template>
            </el-table-column>
            <el-table-column label="导航显示" width="180">
                <template slot-scope="_scope">
                    <el-switch v-model="_scope.row.column_display" active-text="显示" inactive-text="隐藏" @change="column_display(_scope.$index,_scope.row)"></el-switch>
                </template>
            </el-table-column>
            <el-table-column property="other" label="其他操作">
                <template slot-scope="scope">
                    <el-button size="mini" @click="handleEdit(scope.$index, scope.row)">编辑</el-button>
                    <el-button size="mini" type="danger" @click="handleDelete(scope.$index, scope.row)">删除</el-button>
                </template>
            </el-table-column>
        </el-table>
        <!--修改-->
        <template>
            <el-popover title="编辑" trigger="click" v-model="EditVisible" width="500" id="edit_form">
                <el-form ref="form" :model="editForm" label-width="80px">
                    <el-form-item label="分类名称">
                        <el-input v-model="editForm.column_name"></el-input>
                    </el-form-item>
                    <el-form-item label="所属分类">
                        <el-cascader v-model="editForm.column_parent" :options="options" :props="{ expandTrigger: 'hover' }" placeholder="请选择分类"></el-cascader>
                    </el-form-item>
                    <el-form-item label="分类排序">
                        <el-input v-model="editForm.column_order" type="number"></el-input>
                    </el-form-item>
                    <el-form-item label="站外链接">
                        <el-input v-model="editForm.column_link" placeholder="http://"></el-input>
                    </el-form-item>
                    <el-form-item label="关键词">
                        <el-input type="textarea" autosize placeholder="请输入关键词" v-model="editForm.column_keyword"></el-input>
                    </el-form-item>
                    <el-form-item label="分类描述">
                        <el-input type="textarea" v-model="editForm.column_description" :autosize="{ minRows: 2, maxRows: 4}"></el-input>
                    </el-form-item>
                    <el-form-item>
                        <el-button @click.prevent="onEditSubmit" type="success" class="el-button--primary">保存</el-button>
                        <el-button @click="EditVisible = false">取消</el-button>
                    </el-form-item>
                </el-form>
            </el-popover>
        </template>
    </div>
    <script src="{% static 'js/public.js' %}" type="text/javascript"></script>
    <script>
        var Main = {
            data() {
                return {
                    editForm: {column_name: '', column_parent: '', column_order: 0, column_link: '', column_keyword: '', column_description: ''},
                    EditVisible: false,
                    options: [],
                    tableData: [
                        {% for nav in NavList %}
                            {
                                uuid: "{{ nav.uuid }}",
                                column_name: "{{ nav.column_name }}",
                                column_parent: "{{ nav.column_parent|column_parent }}",
                                bookNum: {{ nav.novel_categories.count }},
                                update_time: "{{ nav.update_time }}",
                                column_index_show: "{{ nav.column_index_show }}",
                                column_display: "{{ nav.column_display }}"
                            },
                        {% endfor %}
                    ],
                    form: {column_name: '', column_parent: '', column_order: 0, column_link: '', column_keyword: '', column_description: ''}
                }
            }
            , methods: {
                column_display(index, row) {
                    submit_ajax(this, 'GET', {'uuid': row.uuid, 'column_display': row.column_display}, '{% url 'admin_system:navigationEdit_display' %}', false);
                },
                index_show(index, row) {
                    submit_ajax(this, 'POST', {'uuid': row.uuid, 'column_index_show': row.column_index_show}, '{% url 'admin_system:navigationEdit_display' %}', false);
                },
                handleEdit: function (index, row) {
                    this.onGetCategory();
                    this.EditVisible = true;
                    var response = submit_ajax(this, 'GET', {'uuid': row.uuid}, "{% url 'admin_system:navigationEdit' %}", false, false);
                    if (response.code === 0) {
                        this.editForm = response.data
                    }
                },
                handleDelete: function (index, row) {
                    Delete(this, index, row)
                },
                onAddSubmit() {
                    if (this.form.column_parent !== undefined) {
                        this.form.column_parent = this.form.column_parent.pop();
                    }
                    var response = submit_ajax(this, 'POST', this.form, "{% url 'admin_system:navigationAdd' %}", true, true);
                    if (response.code === 0) {
                        $('#content').click();// 隐藏
                    }
                }, onEditSubmit() {
                    if (this.editForm.column_parent !== undefined && Array.isArray(this.editForm.column_parent)) {
                        this.editForm.column_parent = this.editForm.column_parent.pop();
                    }
                    var response = submit_ajax(this, 'POST', this.editForm, "{% url 'admin_system:navigationEdit' %}", true, true);
                    if (response.code === 0) {
                    }
                },
                onGetCategory() {
                    this.form = {column_order: 0};
                    this.options = [];
                    var response = submit_ajax(this, 'GET', {}, "{% url 'admin_system:navigationAdd' %}", false, false);
                    this.options = response.category;
                    this.options.splice(0, 0, {'label': '顶级分类', 'value': '0'});
                }, cancelClick(scope) {
                    $('#content').click();// 隐藏
                }

            }, mounted() {
                var all = Array();
                for (j = 0, len = this.tableData.length; j < len; j++) {
                    x = this.tableData[j];
                    x['column_index_show'] = x['column_index_show'] === 'True' ? true : false;
                    x['column_display'] = x['column_display'] === 'True' ? true : false;
                    all.push(x)
                }
                this.tableData = all;
            }
        };
        var Ctor = Vue.extend(Main);
        new Ctor().$mount('#app');
        $(function () {
            $('button[class="el-button el-button--primary"]').on('click', function () {
                url = $(this).attr('url');
                window.location.href = url
            })
        })
    </script>
{% endblock %}

system/templates/normalList.html
{% extends 'admin/base.html' %}
{% load custom_filters staticfiles %}
{% block content %}
    <style>
        .cell {
            text-align: center;
        }

        div[class="el-input"] {
            width: 220px;
        }
    </style>
    <div id="app">
        <template>
            <el-table :data="tableData" style="width: 100%" border>
                <el-table-column label="来访IP" prop="ip"></el-table-column>
                <el-table-column label="访问次数" prop="visit"></el-table-column>
                <el-table-column label="初次访问" prop="time"></el-table-column>
                <el-table-column label="最新访问" prop="first_time"></el-table-column>
                <el-table-column label="操作" width="200">
                    <template slot-scope="scope">
                        <el-button size="mini" type="warning" @click="handleEdit(scope.$index, scope.row)">冻结</el-button>
                        <el-button size="mini" type="danger" @click="handleDelete(scope.$index, scope.row)">删除</el-button>
                    </template>
                </el-table-column>
            </el-table>
        </template>
        <br/>

        <el-pagination background layout="prev, pager, next" :total="total" hide-on-single-page @current-change="current_change" :current-page="currentPage" style="text-align: right;"></el-pagination>

    </div>
    <script src="{% static 'js/public.js' %}" type="text/javascript"></script>
    <script>
        var Main = {
            data() {
                return {
                    total: {{ page.pages }}0,
                    currentPage: {{ page.current|default:1 }},
                    tableData: [
                        {% for data in dataList %}
                            {
                                ip: '{{ data.ip }}',
                                uuid: '{{ data.ip }}',
                                visit: '{{ data.visit }}',
                                first_time: '{{ data.first_time|time_str }}',
                                time: '{{ data.time|time_str }}',
                            },
                        {% endfor %}
                    ],
                    formLabelWidth: '120px',
                }
            }
            , methods: {
                handleDelete: function (index, row) {
                    Delete(this, index, row);
                },
                current_change: function (currentPage) {
                    window.location.href = '?page=' + currentPage;
                }, handleEdit: function (index, row) {
                    submit_ajax(this,'POST',{'ip':row.ip})
                }
            }
        };
        var Ctor = Vue.extend(Main);
        new Ctor().$mount('#app');
    </script>
{% endblock %}